### ISSUE TITLE
Not working on .NET Core on Linux?

### ISSUE THREAD

**Issue by wasowski** [rcw3bb/simple-dotnet-core#1]
I am trying to use the plugin on Linux with .NET core. Unfortunately, I could only get the `clean` task to work. I suppose that `clean` works as it is implemented entirely in gradle, without invoking external commands. An attempt to innvoking a build task gives the following message:
```
The simple_dotnet.autoInstall property was set to false.
Please install a .Net Core SDK.
```
I do have .NET core installed and `dotnet build` works on the command line.  I suspect that the plugin does something Windows specific, however,  I was unable to track down what is wrong by quick reading of the source code. This suspicion is purely based on the fact that the automatic installer attempts to use PowerShell (which is why I deactivated it).

**Comment by wasowski** [comment]
Perhaps the problem is this line 

https://github.com/rcw3bb/simple-dotnet-core/blob/c8ecbe55202c1dbc2415baee531ed581931cbc9a/src/main/java/xyz/ronella/gradle/plugin/DotNetExecutor.java#L19

As it seems to fix the executable name to have the `.exe` extension (which it does not have on other platforms than Windows).

**Comment by rcw3bb** [comment]
Hi @wasowski, try the 1.1.3 version.

**Comment by rcw3bb** [comment]
Closing this issue, starting from 1.1.3 linux is now supported.

**Comment by wasowski** [comment]
Thanks for this.  Unfortunately, this was a bit of a fast job, so I found a different solution, and then it was a bit hard for me to revert and test.  I still get slightly confusing results.  The build seems to work with this plugin, but the run task still reports
```
Either the simple_dotnet.autoInstall property was set to false or you are not in a windows operating system.
Please install a .Net Core SDK manually
```
Do you have an idea why?

**Comment by rcw3bb** [comment]
Hi @wasowski, seems it cannot find the dotnet executable in the standard location. Have you tried v1.2.0? However, because of this I will try to refine the dotnet executable detection.

**Comment by rcw3bb** [comment]
Hi @wasowski, please try the v1.3.0 it should detect the location of the dotnet executable as long as it is reachable via the PATH environment variable.

**Comment by wasowski** [comment]
I'll give it a shot within a few days (busy times). I will report back.

**Comment by wasowski** [comment]
v1.3.0 works! Thanks a lot!
