### ISSUE TITLE
`args` cannot be set using Gradle's Kotlin DSL

### ISSUE THREAD

**Issue by alastairs** [rcw3bb/simple-dotnet-core#3]
I'm trying to add this plugin to an existing Gradle project using the Kotlin DSL. I converted [the example](https://github.com/rcw3bb/simple-dotnet-core#example) as follows:

```kotlin
import xyz.ronella.gradle.plugin.simple.dotnet.core.task.DotNetPublishTask

// ... snip ...

tasks.register<DotNetPublishTask>("buildProject") {
  args = arrayOf(
    "-c", "Release",
    "-f", "netcoreapp3.1",
    "-r", "win-x64",
    "-o", "${layout.buildDirectory.dir("bin")}",
    "--self-contained",
    "/p:PublishSingleFile=true",
    "/p:PublishTrimmed=true"
  )
}
```

Unfortunately, as [`args` is defined](https://github.com/rcw3bb/simple-dotnet-core/blob/master/src/main/groovy/xyz/ronella/gradle/plugin/simple/dotnet/core/task/DotNetTask.groovy#L25) as `String[] = []`, it cannot be reassigned using Kotlin which treats immutability much more strongly than Groovy. I haven't been able to find a workaround yet.

**Comment by rcw3bb** [comment]
Hi @alastairs , use version 3.0.0 and update to the following:

```groovy
tasks.register<DotNetPublishTask>("buildProject") {
    args.addAll(
            "-c", "Release",
            "-f", "netcoreapp3.1",
            "-r", "win-x64",
            "-o", "${layout.buildDirectory.dir("bin")}",
            "--self-contained",
            "/p:PublishSingleFile=true",
            "/p:PublishTrimmed=true"
    )
}
```
